import Header from "@/components/Header";
import Footer from "@/components/Footer";

import style from "./layout.module.css";
import "./globals.css";

import { Roboto, Anton } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "900"],
  style: ["italic", "normal"],
  display: "swap",
  variable: "--font-reoboto",
});

const anton = Anton({
  subsets: ["latin"],
  weight: ["400"],
  style: ["normal"],
  display: "swap",
  variable: "--font-anton",
});

export const metadata = {
  title: "ManageStock",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr" className={`${roboto.variable} ${anton.variable}`}>
      <body className={style.body}>
        <Header />
        <main className={style.main}>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
